FROM golang:1.22

WORKDIR /app

COPY . /app


RUN go install github.com/pressly/goose/v3/cmd/goose@latest

ENV PATH=$PATH:/go/bin

ENTRYPOINT ["sh", "-c", "goose -dir=/app/internal/db/migrations postgres \"user=postgres password=qwert dbname=microserv host=postgres sslmode=disable\" up"]
