FROM golang:1.22

WORKDIR /app

COPY . /app

RUN apt-get update && apt-get install -y iproute2

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

ENV PATH=$PATH:/go/bin

ENTRYPOINT ["sh", "-c", "sleep 30 && goose -dir=/app/internal/db/migrations postgres \"user=postgres password=qwert dbname=microserv host=postgres sslmode=disable\" up"]
