# Используйте базовый образ Kafka Connect
FROM debezium/connect:1.7

# Копируйте скрипт и конфигурацию коннектора в контейнер
COPY install-connector.sh /usr/share/confluent/docker/
COPY postgres-connector2.json /usr/share/confluent/docker/

# Сделайте скрипт исполняемым
RUN chmod +x /usr/share/confluent/docker/install-connector.sh
