definitions:
  models.Message_Request:
    properties:
      text:
        description: Набранный текст
        type: string
    type: object
  models.Stats:
    properties:
      pending_messages:
        description: количество необработанных сообщений
        type: integer
      processed_messages:
        description: количество обработанных сообщений
        type: integer
      total_messages:
        description: общее количество сообщений
        type: integer
    type: object
info:
  contact: {}
paths:
  /message:
    post:
      consumes:
      - application/json
      description: Создает новое сообщение и сохраняет его в базе данных
      parameters:
      - description: Сообщение
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/models.Message_Request'
      produces:
      - application/json
      responses:
        "201":
          description: Сообщение успешно создано
          schema:
            $ref: '#/definitions/models.Message_Request'
        "400":
          description: Неверный запрос
          schema:
            type: string
        "500":
          description: Ошибка сервера
          schema:
            type: string
      summary: Создать сообщение
      tags:
      - messages
  /stats:
    get:
      description: Get statistics from the database
      parameters:
      - description: Limit the number of results
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Statistics retrieved successfully
          schema:
            $ref: '#/definitions/models.Stats'
        "500":
          description: Failed to get or encode stats
          schema:
            type: string
      summary: Get statistics
      tags:
      - stats
swagger: "2.0"
